# Plugin RankUp Dành Cho PocketMine
unleash-the-rankupdoesgroups: true
# Nếu Bạn Đặt Thành false Thì RankUpDoesGroups Sẽ Không Được Tải
# Điều Này Có Nghĩa Bạn Không Thể Đặt Nó Làm Người Quản Lý GroupManager
# Rất Khuyến Khích Không Thay Đổi Điều Này
preferred-economy: false
# Đặt Nền Kinh Tế Ưa Thích Của Bạn
# rankup\\economy\\Economy Và rankup\\economy\\PocketMoney Có Sẵn Theo Mặc Định
# Đặt Thành false Để Tự Động Tải(Chỉ Các Nền Kinh Tế Hổ Trợ Chính Thức Mới Tự Động Tải)
preferred-groupmanager: "rankup\\permission\\RankUpDoesGroups"
# Đặt Người Quản Lý Group Ưa Thích Của Bạn
# rankup\\permission\\RankUpDoesGroups Và rankup\\permission\\PurePerms Có Sẵn
# RankUpDoesGroups Là Một Siêu Thay Thế Cho Những Người Không Sử Dụng PurePerms
  
  

# Xác Định Tất Cả Các Rank Tại Đây:
ranks:
  Coal: 15000
  Iron: 20000
  Gold: 27000
  Diamond: 1200000
  King: 1800000
  Master: 5000000
  VIPMaster: 8000000



lang:
  ranked-up-paid: "§eCraft-Legendery༺§dMhúc Mừng Bạn Đã Lên Rank:§e %s"
  ranked-up-free: "§eCraft-Legendery༺§dMhChúc Mừng Bạn Đã Lên Rank:§e %s"
  group-add-error-paid: "§eCraft-Legendery༺§d  Có Lỗi Phát Sinh. Hãy Thông Báo OP Để Khắc Phục"
  group-add-error-free: "§e༺§d CRaft-legenderyó Lỗi Phát Sinh. Hãy Thông Báo OP Để Khắc Phục"
  need-more-money-1: "§e༺§dCraft-legendery Như Bạn Không Đủ Tiền Để Lên Rank. Cố Gắng Lên Nhé!"
  need-more-money-2: "§e༺§9Craft-Legendery§a Bạn Cần:§e %s §aXu Nữa Để Lên Rank"
  missing-economy: "§e༺§9 Craft-legenderyCó Lỗi Phát Sinh. Hãy Thông Báo OP Để Khắc Phục"
  have-max-rank: "§e༺§9Craft-Legendery Rank Của Bạn Đã Cao Nhất. Cảm Ơn Bạn Đã Tham Gia Máy Chủ!"
  command-permission-error: "§e༺§dMinePig§e༻§c Đã Có Lỗi Phát Sinh. Hãy Thông Báo OP Để Khắc Phục"