name: PickaxeLevel
main: PickaxeLevel\phuongaz\Main
api: [2.0.0]
author: phuongaz
version: 4.0
commands:
 givecup:
  description: Give MINE DRAGON pickaxe to player
  default: op
 topcup:
  description: Xếp hạng cấp cúp
  default: true
 