---
datetime-format: "H:i:s"

stopServer:
    custom: true
    messge: "§e máy Chủ Đóng Cửa"
death-magic-message:
    hide: false
    custom: true
    message: "§7§l[ §6{PLAYER} §7] §5Bị Chết Bằng Một Ma Thuật Nào Đó §f≥﹏≤"
death-void-message:
    hide: false
    custom: true
    message: "§7§l[ §6{PLAYER} §7] §9Đã Bị Rơi Ra Ngoài Thế Giới Vì Lí Do Nào Đó §f(ㄒoㄒ)"
FullServer:
  custom: true
  message: "§l§e{PLAYER}&b, Server Này Đã Đầy &c[{TOTALPLAYERS}/{MAXPLAYERS}]&b!\n&l&dHãy Vào Lại Sau"
WhitelistedServer:
  custom: true
  message: "§c§lMáy Chủ Này Đã Được Đưa Vào §fBảo Trì!"
OutdatedServer:
  custom: true
  message: "§l§cRất Tiếc! Máy Chủ Đã Bị Lỗi!"
FirstJoin:
  enable: true
  message: "§l§7[ §6{PLAYER} §7]§e Lần Đầu Tiên Vào §cServer §f(｡’▽’｡)"
Join:
  hide: false
  custom: true
  message: "§l§7 ┗ §6{PLAYER} §7┓§b Đã Tham Gia §cMáy Chủ §f(･´з`･)"
WorldChange:
  enable: false
  message: "..."
Quit:
  hide: false
  custom: true
  message: "§l§7[ §6{PLAYER} §7]§e Đã Thoát Khỏi §cMáy Chủ §f(*>.<*)"
Death:
  hide: false
  custom: true
  kill-message: "§l§7[ §6{PLAYER} §7] &d§dĐã Bị Thông Bởi §c{KILLER} §fΣ(っﾟДﾟ；)っ"
  death-default-message: "§l§7[ §6{PLAYER} §7] §bĐã Chết Vì Lí Do Nào Đó §f(ㄒoㄒ)"
  death-suffocation-message: "§l§7[ §6{PLAYER} §7] §aNghẹt Thở Đến Chết §f(✖﹏✖)"
  death-fall-message: "§l§7[ §6{PLAYER} §7] §bĐã Bị Chết Vì Rơi Xuống Một Độ Cao Nào Đó §fΣ( ° △ °|||)"
  death-fire-message: "§7§l[ §6{PLAYER} §7] §6Đã Bị Chết Vì Đứng Quá Lâu Trong Lửa §f( ●︿● )"
  death-lava-message: "§l§7[ §6{PLAYER} §7] §aBị Chết Dưới Lava §fっ╥╯﹏╰╥c"
  death-drowning-message: "§l§7[ §6{PLAYER} §7] §bĐã Bị Chết Đuối Dưới Nước §f(๑-﹏-๑"
  death-explosion-message: "§l§7[ §6{PLAYER} §7] §2Đã Bị Chết Vì Nổ §f( ￣へ￣ )"
OutdatedClient:
  custom: true
  message: "§l§cPhiên Bản §aMinecraft §c Của Bạn Không Tương Thích Với Server Này!\n§7[§b1.1.x§7]"                                                             