# Config file for TimeCommander by LDX;

# List of commands for the plugin to execute at the given times;
# Command: Command to execute;
# Time: Amount of time in minutes between command executions;
Commands:
  - Command: time set day
    Time: 5
  - Command: save-all
    Time: 5
  - Command: reload
    Time: 60
